name: DiscordJS Bot

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22]  # Use the latest Node.js version

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - name: Install Dependencies
        run: |
          npm ci --cache .npm
      - name: Build and Run
        env:
          TOKEN: ${{ secrets.TOKEN }}
          MONGO: ${{ secrets.MONGO }}
        run: |
          # Build your project here, if necessary
          npm install nodemon -g
          node shards.js
